// import Head from 'next/head'
// import Image from 'next/image'
// import HeaderCpn from "@/components/layouts/headerCpn";
// import FooterCpn from "@/components/layouts/footerCpn";

// import mainStyles from '../../index.module.scss';

// function ProductsManager() {
//     return (
//         <>
//             <div>
//                 <Head>
//                     <title>Quản lý nhóm sản phẩm </title>
//                     <meta name="description" content="Generated by create next app" />
//                     <meta name="viewport" content="width=device-width, initial-scale=1" />
//                     <link rel="icon" href="/favicon.ico" />
//                 </Head>
//             </div>
//             <div>
//                 <HeaderCpn></HeaderCpn>
//                 <div className={`${mainStyles.bodySec}`}>
//                 </div>
//                 <FooterCpn></FooterCpn>


//             </div>
//         </>);
// }

// export default ProductsManager;