import { useRouter } from 'next/router'
import { useState, useEffect } from 'react';
import moment from 'moment';
import Head from 'next/head'

import mainStyles from '../index.module.scss';
import HeaderCpn from "@/components/layouts/headerCpn";
import FooterCpn from "@/components/layouts/footerCpn";
import blogsApi from '@/api/blogs';
function Blog({ data }) {
    const router = useRouter();
    const [blogTitle, setBlogTitle] = useState('');
    const [blogContent, setBlogContent] = useState('');
    const [timeCreated, setTimeCreated] = useState('');


    useEffect(() => {
        setBlogTitle(data.blog.data.blog.title);
        setBlogContent(data.blog.data.blog.content);
        setTimeCreated(moment(data.blog.data.blog.createdAt).format('HH:mm DD-MM-YYYY'))
        console.log(data.blog.data.blog);
    }, [data])

    return (
        <>

            <div>
                <Head>
                    <title>{blogTitle}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            </div>
            <div>
                <HeaderCpn></HeaderCpn>
                <div className={`${mainStyles.bodySec}`} >
                    <div className={`d-flex justify-content-start`}>
                        <h3>{blogTitle}</h3>
                    </div>
                    <div className={`d-flex justify-content-end`}>
                        <h6>{timeCreated}</h6>
                    </div>
                    <div dangerouslySetInnerHTML={{ __html: blogContent }}>
                    </div>
                </div>

                <FooterCpn></FooterCpn>


            </div>
        </>
    );
}

export async function getServerSideProps(context) {
    let data = {};
    let blogData = await blogsApi.getBlogs(context.query.blogId);
    console.log('check block data : ', blogData.data);
    data.blog = blogData.data;
    return { props: { data } }
}


export default Blog;