// import Head from 'next/head'
// import Image from 'next/image'
// import Link from 'next/link';
// import HeaderCpn from "@/components/layouts/headerCpn";
// import FooterCpn from "@/components/layouts/footerCpn";
// import { useEffect, useState } from 'react';
// import { ToastContainer, toast } from 'react-toastify';
// import 'react-toastify/dist/ReactToastify.css';
// import { useRouter } from 'next/router';
// import { Button } from 'react-bootstrap';
// import { DataView } from 'primereact/dataview';
// import { Tag } from 'primereact/tag';
// import { Button as PrimeReactButton } from 'primereact/button';
// import {
//     faPenToSquare,
//     faPlus,
//     faList,
// } from "@fortawesome/free-solid-svg-icons";
// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import 'primeflex/primeflex.css';
// import "primereact/resources/themes/lara-light-indigo/theme.css";
// import "primereact/resources/primereact.min.css";
// import { Carousel, Dropdown } from "react-bootstrap";
// import { connect } from 'react-redux';
// import moment from 'moment';

// import mainStyles from '../index.module.scss';
// import blogsApi from '@/api/blogs';

// function Blogs({ data }) {

//     const [requestData, setRequestData] = useState([]);
//     useEffect(() => {
//         // console.log('check data blogs : ', data.blogs.data.blogs);
//         setRequestData(data.blogs ? data.blogs.data.blogs : []);
//     }, [data])


//     const itemTemplate = (request) => {
//         // console.log('--->check product cate name: ', product.Product_Category);
//         return (
//             <div className="col-12">
//                 <div className="d-flex justify-content-start p-4 gap-2">
//                     <Link style={{ cursor: 'pointer', textDecoration: 'none', }} href={"/blogs/" + request.routeSlug} >
//                         <div className="d-block justify-content-center">
//                             <div className="text-l font-bold text-900">{request.title}</div>
//                             <div className="text-m font-bold text-500"> Ngày đăng : {moment(request.createdAt).format('HH:mm DD-MM-YYYY')}</div>
//                         </div>
//                     </Link>
//                 </div>
//             </div>
//         );
//     };
//     return (
//         <>
//             <div>
//                 <Head>
//                     <title>Danh sách bài viết </title>
//                     <meta name="description" content="Generated by create next app" />
//                     <meta name="viewport" content="width=device-width, initial-scale=1" />
//                     <link rel="icon" href="/favicon.ico" />
//                 </Head>
//             </div>
//             <div>
//                 <HeaderCpn></HeaderCpn>
//                 <div className={`${mainStyles.bodySec}`} >
//                     <div className="card">
//                         <DataView value={requestData} itemTemplate={itemTemplate} paginator rows={10} />
//                     </div>
//                 </div>
//                 <ToastContainer />

//                 <FooterCpn></FooterCpn>
//             </div>
//         </>
//     );
// }

// export async function getServerSideProps() {
//     let data = {};
//     let blogs = await blogsApi.getAllBlogs();
//     data.blogs = blogs.data;
//     // console.log(requests.data);
//     return { props: { data } }
// }

// export default Blogs;